project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"

website:
  title: "Brianna Heggeseth"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Social Justice
        menu: 
          - inclusion.qmd
          - awareness.qmd
          - href: climate.qmd
            text: Classroom Climate
          - href: design.qmd
            text: Course Design
          - href: https://docs.google.com/document/d/1dqqrTC1P4X7M5usZoPVM-WxTDNxeBhFWK9iCAs5Vy0s/edit?usp=sharing
            text: Institutional Culture
          - href: https://docs.google.com/document/d/1MZcQbc4hHiyTqsKbhC6qGsyk8EqvZkA1koSD9mu7PPI/edit?usp=sharing
            text: Academic Hiring
      - href: teaching.qmd
        text: Teaching
      - text: Student Resources
        menu:
          - internships.qmd
          - datasets.qmd
      - text: Projects
        menu: 
          - href: projects.qmd
            text: "Scholarly Data Projects"
          - href: https://www.causeweb.org/jedi/
            text: "JEDI-Informed Teaching Resources"
          - href: tidytuesday.qmd
            text: "Tidy Tuesday"
 
  page-footer:
    left: |
      &copy; Brianna Heggeseth, 2023<br>
      All content licensed under <i class='bi-badge-cc'></i>
      [(CC BY-NC-SA 4.0)](http://creativecommons.org/licenses/by-nc-sa/4.0/)
    right: |
      Site built with <a href='https://quarto.org/'>Quarto</a>

format:
  html:
    theme: [yeti, theme.scss]
    toc: true

editor: visual

