project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"

website:
  title: "Brianna Heggeseth"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Social Justice
        menu: 
          - inclusion.qmd
          - awareness.qmd
          - climate.qmd
          - design.qmd
      - text: Teaching
        menu:
          - teaching.qmd
          - datasets.qmd
      - projects.qmd
  page-footer:
    left: |
      &copy; Brianna Heggeseth, 2023<br>
      All content licensed under <i class='bi-badge-cc'></i>
      [(CC BY-NC-SA 4.0)](http://creativecommons.org/licenses/by-nc-sa/4.0/)
    right: |
      Site built with <a href='https://quarto.org/'>Quarto</a>

format:
  html:
    theme: superhero
    css: styles.css
    toc: true

editor: visual

