---
title: "Raising Awareness"
---

## Implicit Bias

We all have implicit biases. Even those who study implicit bias have implicit bias. 

- Take a few [Harvard Implicit Bias Tests](https://implicit.harvard.edu/implicit/takeatest.html)



## Diverse Perspectives

### Social Media Worth Following

- Twitter
  - [@ReadBlackademia](https://twitter.com/readblackademia)
  - [#BlackintheIvory](https://twitter.com/hashtag/BlackintheIvory)
  - [@VanguardSTEM](https://twitter.com/VanguardSTEM)
  - [#DiversityandInclusion](https://twitter.com/hashtag/DiversityandInclusion) 
  - [@500QueerSci](https://twitter.com/500QueerSci) 
  - [@QueersInSTEM](https://twitter.com/QueersInSTEM)



### My Reading List

As a white cis-gender woman, these are some books that I'm reading to expand my awareness on others life experiences. Suggestions welcome!

#### Statistics-Specific

[Understanding the Burdens of Race at a Predominantly White University: The experiences of underrepresented students in an introductory statistics courses](http://iase-web.org/documents/dissertations/07.Davidson.Dissertation.pdf); PhD Dissertation by Mario Antonio Davidson

#### Racial Inequity


[From Equity Talk to Equity Walk](https://www.aacu.org/publications-research/publications/equity-talk-equity-walk-expanding-practitioner-knowledge-racial) by Tia Brown McNair, Estela Mara Bensimon and Lindsey Malcom-Piqueux

[Why Are All the Black Kids Sitting Together in the Cafeteria: And Other Conversations About Race](https://www.mprnews.org/story/2017/10/10/why-are-all-the-black-kids-sitting-together-in-the-cafeteria) by Beverly Daniel Tatum

[Caste](https://www.npr.org/2020/08/04/898574852/its-more-than-racism-isabel-wilkerson-explains-america-s-caste-system) by Isabel Wilkerson

[So you want to talk about race](https://www.sealpress.com/titles/ijeoma-oluo/so-you-want-to-talk-about-race/9781580056779/) by Ijeoma Oluo

[Between the World and Me](https://www.penguinrandomhouse.com/books/220290/between-the-world-and-me-by-ta-nehisi-coates/) by Ta-Nehisi Coates

[The Making of Asian America: A History](http://www.erikalee.org/the-making-of-asian-america/) by Erika Lee

[Yellow: Race in America Beyond Black and White](https://www.basicbooks.com/titles/frank-h-wu/yellow/9780465006403/) by Frank Wu

[How to be Anti-Racist](https://www.ibramxkendi.com/how-to-be-an-antiracist) by Ibram X. Kendi

[All Speech is Not Free](https://www.jstor.org/stable/42978376) by Megan Boler


#### White Privilege

[The Myth of Equality: Uncovering the Roots of Injustice and Privilege](https://www.ivpress.com/the-myth-of-equality) by Ken Wytsma

[White Awake: An Honest Look at What It Means to Be White](https://www.ivpress.com/white-awake) by Daniel Hill

[America's Original Sin: Racism, White Privilege, and the Bridge to a New America](https://americasoriginalsin.com/) by Jim Wallis

[Understanding White Privilege: Creating Pathways to Authentic Relationships Across Race (Teaching/Learning Social Justice)](https://www.routledge.com/Understanding-White-Privilege-Creating-Pathways-to-Authentic-Relationships/Kendall/p/book/9780415874274) by Frances Kendall

[White Fragility](https://www.robindiangelo.com/publications/) by Robin DiAngelo


#### Neurodiversity & Universal Design

[Neurotribes: The Legacy of Autism and the Future of Neurodiversity](https://www.penguinrandomhouse.com/books/310415/neurotribes-by-steve-silberman-foreword-by-oliver-sacks/) by Steve Silberman

[Universal Design in Higher Education, From Principles to Practice](https://www.hepg.org/hep-home/books/universal-design-in-higher-education) by Sheryl E. Burgstahler