---
title: "JEDI Definitions"
---

Everyone has their own concept of what justice, equity, diversity, and inclusion (JEDI) means to them. I provide the definitions that frame my pedagogical and professional work.

### What is Diversity?

There are many ways in which people differ, both in terms of visiblee and invisible characteristics that influences individual and group identity and life experience. These characteristics may include, but are not limited to, race, ethnicity, color, sex, sexual orientation, gender identity, gender expression, socio-economic status, language, culture, national origin, religion/spirituality, age, (dis)ability, and military/veteran status.

We should celebrate our differences! We benefit from having learning spaces that include a diverse group of individuals and perspectives because our own lived experiences provide a narrow view of the world. We can deepen our understanding of our world, develop more creative and better solutions to important societal problems by having many ideas and approaches expressed.

### What is Equity?

But it is not enough for everyone "a seat at the table." Our society was built on the foundations of colonization and oppression, a caste system, which set the rules to benefit some groups, individuals, and identities over others. We must work to counter uneven social power and white supremacy.

We should make sure that everyone has the support and opportunity they need to succeed. Equity does not necessarily mean equal support and opportunity as we do not all experience the same barriers. We must put policies in place to actively respond to systematic racism and other forms of discrimination, bias, and harassment.

### What is an Inclusion?

Inclusion means actively cultivating an environment where everyone feels welcome and valued. An inclusive space can only be created once we are more aware of our unconscious biases and the roles we play in the social power dynamics, and have learned and are actively working to counter them.

Only with equity and inclusion can a diverse group of individuals thrive.

### What is Justice?

Justice means dismantling barriers to resources and opportunities in society so that all individuals & communities can live a full & dignified life.

### What is an Inclusive & Equitable Classroom?

An inclusive and equitable classroom is a space in which all students feel like they **belong**; they feel welcomed into the intellectual discussion, **supported** in their learning, and **valued** for their ideas and contributions.

All students have full access to learning opportunities, and the tools they need to do so successfully and meaningfully.

Students are treated **fairly** and **equitably**, not necessarily equally, no matter their background and intersecting identities (e.g. race, ethnicity, socioeconomic class, gender identity/expression, sexual orientation, religion, nationality, ability, age,...)
